apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi
  name: multi
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo multi1;sleep 3600
    image: busybox
    name: multi1
    resources: {}
  - args:
    - /bin/sh
    - -c
    - ls
    image: busybox
    name: multi2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
