apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx-green
spec:
  replicas: 3
  selector:
    matchLabels:
     version: green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
       version: green
    spec:
      containers:
      - image: nginx:1.23.4
        name: nginx
        resources: {}
        ports:
        - containerPort: 80
status: {}
