apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      version: blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        version: blue
    spec:
      containers:
      - image: nginx:1.23.0
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
