apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-mount
  name: nginx-mount
spec:
  volumes:
  - name: logs-volume
    persistentVolumeClaim:
      claimName: logs-pvc
  containers:
  - image: nginx
    name: nginx-mount
    resources: {}
    volumeMounts:
    - mountPath: "/var/log/nginx"
      name: logs-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
