apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-server
  name: web-server
spec:
  containers:
  - image: nginx:1.23.0
    name: web-server
    ports:
    - containerPort: 80
      name: nginx-port
    resources: {}
    startupProbe:
     httpGet:
      path: /
      port: nginx-port
    readinessProbe:
     httpGet:
      path: /
      port: nginx-port
     initialDelaySeconds: 5
    livenessProbe:
     httpGet:
      path: /
      port: nginx-port
     initialDelaySeconds: 10
     periodSeconds: 30
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
