apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: complex-pod
  name: complex-pod
spec:
  initContainers:
  - image: busybox:1.36.1
    name: setup
    command:
    - /bin/sh
    - -c
    - wget -O- google.com
  containers:
  - image: nginx:1.25.1
    name: app
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
