apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: deploy
  name: deploy
spec:
  containers:
  - args:
    - nginx
    image: nginx:1.18.0
    name: deploy
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
