apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  volumes:
  - name: container-vol
    emptyDir: {} 
  containers:
  - image: alpine:3.12.0
    name: pod1
    args:
    - /bin/sh
    - -c
    - while true; do sleep 60; done;
    volumeMounts:
    - name: container-vol
      mountPath: /etc/a
    resources: {}
  - image: alpine:3.12.0
    name: pod2
    args:
    - /bin/sh
    - -c
    - while true; do sleep 60; done;
    volumeMounts:
    - name: container-vol
      mountPath: /etc/b
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
