apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
spec:
  volumes:
  - name: config-vol
    configMap:
     name: config
  containers:
  - image: nginx:1.23.4-alpine
    name: backend
    resources: {}
    volumeMounts:
    - name: config-vol
      mountPath: /etc/config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
