apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: loop-endless
  name: loop-endless
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do date; sleep 10; done
    image: busybox:1.36.1
    name: loop-endless
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
