apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-security-context
  name: busysecure
spec:
  securityContext:
     runAsUser: 1000
     runAsGroup: 3000
  volumes:
  - name: evol
    emptyDir: {}
  containers:
  - command: ["sh","-c", "sleep 1h"]
    image: busybox:1.36.1
    name: busybox-security-context
    resources: {}
    securityContext:
     runAsUser: 1000
     runAsGroup: 3000
     allowPrivilegeEscalation: false
    volumeMounts:
    - name: evol
      mountPath: /data/test
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
