apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-world
  name: hello-world
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
  containers:
  - image: bmuschko/nodejs-hello-world:1.0.0
    name: hello-world
    ports:
    - containerPort: 3000
    resources: 
     requests:
      cpu: 100m
      memory: 500Mi
      ephemeral-storage: 1Gi
     limits:
      memory: 500Mi
      ephemeral-storage: 2Gi
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
