apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: data-exchange
  name: data-exchange
spec:
  volumes:
  - name: test-vol
    emptyDir: {}
  containers:
  - command: ['sh','-c','counter=1;while true;do touch "/tmp/$counter-data.txt"; counter=$((counter+1)); sleep 5;done']
    image: busybox:1.36.1
    name: main-app
    volumeMounts:
    - name: test-vol
      mountPath: "/tmp/"
    resources: {}
  - command: ['sh', '-c', 'while true; do ls -d /tmp/*-data.txt \
              | wc -l; sleep 30; done']
    image: busybox:1.36.1
    name: sidecar
    volumeMounts:
    - name: test-vol
      mountPath: "/tmp/"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
